# Generated by Django 3.1.6 on 2021-06-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210603_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='is_rep',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='folder',
            name='is_rep',
            field=models.BooleanField(),
        ),
    ]
